name: OK4KiOS
options:
  bundleIdPrefix: com.fongmi
  xcodeVersion: "15.0"
  projectFormat: xcode15_0
  deploymentTarget:
    iOS: "15.0"
configs:
  Debug: debug
  Release: release
settings:
  base:
    SWIFT_VERSION: 5.9
    TARGETED_DEVICE_FAMILY: "1,2"
packages:
  KSPlayer:
    url: https://github.com/kingslay/KSPlayer.git
    exactVersion: 2.3.4
  SwiftSoup:
    url: https://github.com/scinfu/SwiftSoup.git
    exactVersion: 2.7.6
targets:
  OK4KiOS:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: OK4KiOS
    dependencies:
      - package: KSPlayer
      - package: SwiftSoup
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.fongmi.ok4k.ios
        INFOPLIST_FILE: OK4KiOS/Resources/Info.plist
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
        MARKETING_VERSION: 0.4.0
        CURRENT_PROJECT_VERSION: 7
    scheme:
      testTargets:
        - OK4KiOSTests
  OK4KiOSTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Tests
    dependencies:
      - target: OK4KiOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.fongmi.ok4k.ios.tests
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
